### ISSUE TITLE
Feedback on MIXML - loss of verbose output previously in language=raw

### ISSUE THREAD

**Issue by kieranjol** [MediaArea/MediaAreaXml#14]
I noticed that using language=raw with MIXML doesn't produce multiple strings as is the case with the standard xml library. Using the older xml library, there were multiple options for things like Duration/Filesize. I particularly liked using Duration_String4 as it provided HH:MM:SS:FF. It seems that there is just one method of expressing each metadata element with the new library?
I suppose it's good to have consistency, and it should be possible to add in an external script to transform the current expression to whatever format a user wants. 

Will the old library still be available in future versions or will it be removed in favour of MIXML?

P.S, it's great to see that an xsd for mediainfo is coming together.

**Comment by JeromeMartinez** [comment]
> It seems that there is just one method of expressing each metadata element with the new library

Right, the idea is to limit the size of the XML report, avoiding as much as possible redundant items which can be computed externally (e.g. for HH:MM:SS:FF, this is computed from duration and frame rate).

I understand that multiple forms for the same value was something appreciated (I had got a lot of feedback about it in the past years, but more in the text output: any person can take his prefered form), so we may need to think to how to make everywone happy with this new XML, without external tools. maybe the support of the -f flag for this new XML (but the question is about the XSD: I am not sure I want to consider other forms for a field as something "standardized").

> Will the old library still be available in future versions or will it be removed in favour of MIXML?

Old XML is planned to stay several years at the minimum (I remove old features very rarely).

> P.S, it's great to see that an xsd for mediainfo is coming together.

thanks to @dericed 

***
Thank you for your early feedback, appreciated.

**Comment by JeromeMartinez** [comment]
MediaInfo has now the capability to receive the MIXML as input and outputs the text (default) or old XML format ( `--Output=OLDXML`)  from only the XML (no need of parsing again the file).
I think it fits all cases, reopen the issue if it is not the case.
