### ISSUE TITLE
XSD and XML data conflicts

### ISSUE THREAD

**Issue by ptr727** [MediaArea/MediaAreaXml#32]
Now that v17 supports XSD I am converting my app from manual XPath to XSD generated C# parsing.
I'm running into problems with the generated XML not matching the XSD.

XSD says Channels is numeric, sample XML says channels is text:
```
<Channels>8 / 6</Channels>
<xsd:element name="Channels" minOccurs="0" maxOccurs="1" type="xsd:integer"/>
```
```
<BitRate>2538337 / 1509000</BitRate>
<xsd:element name="BitRate" minOccurs="0" maxOccurs="1" type="xsd:float"/>
```

I also tried two online validators, both report problems.

http://www.utilities-online.info/xsdvalidation/
```
Not valid.
Error - Line 92, 37: org.xml.sax.SAXParseException; lineNumber: 92; columnNumber: 37; cvc-datatype-valid.1.2.1: '2538337 / 1509000' is not a valid value for 'float'.
Error - Line 92, 37: org.xml.sax.SAXParseException; lineNumber: 92; columnNumber: 37; cvc-type.3.1.3: The value '2538337 / 1509000' of element 'BitRate' is not valid.
Error - Line 93, 27: org.xml.sax.SAXParseException; lineNumber: 93; columnNumber: 27; cvc-datatype-valid.1.2.1: '8 / 6' is not a valid value for 'integer'.
Error - Line 93, 27: org.xml.sax.SAXParseException; lineNumber: 93; columnNumber: 27; cvc-type.3.1.3: The value '8 / 6' of element 'Channels' is not valid.
```

https://www.freeformatter.com/xml-validator-xsd.html
```
Cvc-datatype-valid.1.2.1: '2538337 / 1509000' Is Not A Valid Value For 'float'., Line '91', Column '37'.
Cvc-type.3.1.3: The Value '2538337 / 1509000' Of Element 'BitRate' Is Not Valid., Line '91', Column '37'.
Cvc-datatype-valid.1.2.1: '8 / 6' Is Not A Valid Value For 'integer'., Line '92', Column '27'.
Cvc-type.3.1.3: The Value '8 / 6' Of Element 'Channels' Is Not Valid., Line '92', Column '27'.
```

Request:
XSD says StreamOrder is optional, XML samples show StreamOrder missing for subtitles.
Ok, but can StreamOrder please be added for all streams?
ID is defined as text, normally numeric, sometimes text (e.g. 3-CC1), need some form of reliable numeric track identifier.

Sample XML file attached.
[Sample1.zip](https://github.com/MediaArea/MediaAreaXml/files/1444578/Sample1.zip)

**Comment by dericed** [comment]
This is what I was worried about in https://github.com/MediaArea/MediaAreaXml/pull/31#issuecomment-340259339.

**Comment by JeromeMartinez** [comment]
> XSD says Channels is numeric, sample XML says channels is text

Definitely an issue with streams having a legacy layer. I'll check more.

> XSD says StreamOrder is optional, XML samples show StreamOrder missing for subtitles.
> Ok, but can StreamOrder please be added for all streams?

Please 1 issue per ticket, here it is completely different (not a bug, it is a feature request).
Please add another ticket for that.

> ID is defined as text, normally numeric, sometimes text (e.g. 3-CC1), need some form of reliable numeric track identifier.

Same (please a different ticket).
But with some proposal, requesting something impossible to do does not help, so e.g. say technically which content you'll put instead of "3-CC1", taking in account all possibilities (e.g. which "numeric" would you use when a Dolby E stream has 8 audio services and the stream is across tracks having track ID 7 and 8?)

**Comment by ptr727** [comment]
Thank you, done, https://github.com/MediaArea/MediaInfo/issues/201
