### ISSUE TITLE
Language identified as "en", FFProbe and MKVMerge identifies as "und"

### ISSUE THREAD

**Issue by ptr727** [MediaArea/MediaAreaXml#34]
I ran into a sample where MediaInfo identifies the track language as "en", while FFProbe and MKVMerge identifies the language as "und".

MediaInfo:
```
<Language>en</Language>
```

FFProbe:
```
"tags": {
    "LANGUAGE": "und",
```

MKVMerge:
```
"tag_language": "und",
```

Sample file: https://1drv.ms/u/s!AqeqhT0NczrNh9NV0OXdHQk-2Kk5Pw

**Comment by JeromeMartinez** [comment]
As you describe, "und" LANGUAGE is in tags (so "free" to edit, without specific meaning), not in Matroska elements dedicated to language.
MediaInfo provides the language of the track, not the "free" edition tags especially when they conflict with real Matroska elements.

Note: FFmpeg looks like to override Language element (the one which should have the priority) with the LANGUAGE tag: if I remove the Tags in the file, FFmpeg detects English everywhere. I think it is a FFmpeg bug.

VLC:
![image](https://user-images.githubusercontent.com/1641638/32714653-22b85c9a-c84f-11e7-85b2-6769376f230d.png)

MKVToolnix:
![image](https://user-images.githubusercontent.com/1641638/32714684-408633e6-c84f-11e7-943d-a7745db67e85.png)

@robUx4 maybe we need to be more explicit in Matroska specs and say that tags can not override the value of any other Matroska element.

@ptr727 this repository is for MediaArea XML specific issues, please use [MediaInfoLib issue tracker](https://github.com/MediaArea/MediaInfoLib/issues) next time for issues related to detection of metadata in files (this is issue is not related to XML, as it is also there for text, HTML... outputs).

**Comment by ptr727** [comment]
Hmm, interesting, I noticed some of the language tags from these samples are written in capitals, while normally I find them lowercase. Wonder it it is he writing application?

Could you elaborate a bit more on what you mean by tags vs. elements, is this output scheme or internal structure related?
I read the language value from the same location in the JSON all the time, and language only shows up in one place in the JSON schema for MKVMerge and FFProbe.

Ok, I'll try to pick more selectively between lib and xml issues.

**Comment by JeromeMartinez** [comment]
> Hmm, interesting, I noticed some of the language tags from these samples are written in capitals, while normally I find them lowercase. Wonder it it is the writing application?

There is a difference between Matroska dedicated elements "hey, here is the language of the track" and tags part ("put here everything you want", and someone decided to put "LANGUAGE" here).

> Could you elaborate a bit more on what you mean by tags vs. elements, is this output scheme or internal structure related?

Hum, trying with an example.
Imagine a comment from ptr727 with text "comment is written by blabla".
Here, MediaInfo (and VLC and MKVToolnix) analyses the file and say that the comment is written by ptr727, and FFmpeg says that the comment is written by blabla. (which is not a so bad idea, for e.g. the author is not filled in the corresponding place; but here it is wrong because we trust more the author field than the content written by the user).

> I read the language value from the same location in the JSON all the time, and language only shows up in one place in the JSON track schema for MKVMerge and FFProbe.

In FFmpeg text output, you can see the language in 2 places: just after the stream identifier "0:0" in parenthesis and here is should be the real language, and in metadata (so "und" in normal here).
In practice, your file was actually edited (was previously "und", I can see the previous version in a place in the file), but the editor did not change the tag part (for a good reason, not expected to be there) and looks like FFmpeg is fooled by that.

**Comment by ptr727** [comment]
I need to look at this more, scratch head.
I looked at ffmpeg, ffprobe, mediainfo, and mkvmerge output, and other than capitalization of LANGUAGE in ffprobe output, I see no difference between this output and other files where the three tools agree that "und" is "und"?

**Comment by JeromeMartinez** [comment]
I don't get your issue, with now knowing that LANGUAGE tag is only a tag (and not the language) and that FFmpeg has a bug using LANGUAGE tag for language.

> I see no difference between this output and other files where the three tools agree that "und" is "und"?

The difference is that FFmpeg uses non standard LANGUAGE tag for setting the language, if I well understood how FFmpeg handles the LANGUAGE tag.
Remind that non standard LANGUAGE tag has **no** direct information about a track language. What you see in the "tags" part is only tags, not something else (i.e. not the track language) except for tools trying wrongly to catch the track language from the LANGUAGE tag (note: it is not a bd idea to try to find the language from a tag when track language dedicated element is not present, but here issue with FFmpeg is that the non standard LANGUAGE tag looks like to have the priority the standard track language Matroska element).

**Comment by JeromeMartinez** [comment]
here, for this ticket, please close it if you can not provide a file not well detected by MediaInfo (i.e. you need to be able to prove that MediaInfo is buggy with a specific file, which is not the case with the file you provided as the file is explicitly indicated as having English tracks, MKVToolnix from one of the Matroska authors is very explicit about the fact it is English, I provided the screenshot)

**Comment by ptr727** [comment]
Got it, agree, does look like a ffprobe bug:
MKVMerge --Identify:
```
  "tracks": [
    {
      "codec": "MPEG-4p10/AVC/h.264",
      "id": 0,
      "properties": {
        "codec_id": "V_MPEG4/ISO/AVC",
...
        "language": "eng",
...
        "tag_language": "und",
        "uid": 1
      },
      "type": "video"
    },
