### ISSUE TITLE
Matrix_Channels listed twice

### ISSUE THREAD

**Issue by ablwr** [MediaArea/MediaAreaXml#36]
Hi hi,

While integrating MediaConch into Archivematica, @jrwdunham noticed that Matrix_Channels is listed twice in the mediainfo XSD found at https://mediaarea.net/mediainfo/mediainfo_2_0.xsd when using 18.03 of MediaConch, which throws an XML error.

It looks like this bug was introduced in [this commit](https://github.com/MediaArea/MediaAreaXml/commit/01d58744a61525acaec34d96f8b3793ec47413b5#diff-3bc279e07020b62f2a704d36d3414d7e).

**Comment by dericed** [comment]
One area where Jerome and I never easily find agreement is the handling of letter case.
