### ISSUE TITLE
Breaking change in MediaInfo Schema: Typo in TimeCode_Striped field

### ISSUE THREAD

**Issue by plondino** [MediaArea/MediaAreaXml#57]
Prior to 22.09, the output of the Other section had the fields:

```
<TimeCode_Striped>Yes</TimeCode_Striped>      
<TimeCode_Striped_String>Yes</TimeCode_Striped_String>
```

In 22.09, these fields appear to have been renamed:
```
<TimeCode_Stripped>Yes</TimeCode_Stripped>      
<TimeCode_Stripped_String>Yes</TimeCode_Stripped_String>      
```

The schema still reflects the old names.  This is a breaking change and appears to be a typo in the field as "Striped" seems corrrect.

**Comment by plondino** [comment]
I see that it's intentional - I was thinking that "Striped" meant timecode where the timecode is set as a metadata value indicating the first frame, and the rest of the values are interpolated by adding a frame number to that start value.  This is in contrast to e.g. VITC where a timecode value is stored for every frame and is independent of a starting value.

I am unclear on what "Stripped" means in this context, but if it's confirmed intentional I can update the schema on my end.

**Comment by JeromeMartinez** [comment]
> The schema still reflects the old names. This is a breaking change and appears to be a typo in the field as "Striped" seems corrrect.

From [stripped vs. striped](https://www.dictionary.com/compare-words/stripped-vs-striped), the idea (not from me but I don't find again the source of this field name choice, it was years ago) is "stripped: containing the bare essentials" as this field is "Yes" if there is only a start time code.

Note also that this field was buggy with MP4/MOV in previous versions.

**Comment by JeromeMartinez** [comment]
Apologizes @plondino for the XSD not enough maintained, we'll work on having a better update of the XSD when we add/change things in MediaInfo.
