### ISSUE TITLE
Missing AudioChannelsTotal from schema

### ISSUE THREAD

**Issue by plondino** [MediaArea/MediaAreaXml#66]
The new version of MediaInfo has an "AudioChannelsTotal" property but it is missing from the schema:

`<Audio_Channels_Total>14</Audio_Channels_Total>`

Can this be updated?

**Comment by JeromeMartinez** [comment]
[It was added in the repo during the release](https://github.com/MediaArea/MediaAreaXml/pull/63) but not uploaded on the server :(.
We definitely need to automate this part...
Done.
