### ISSUE TITLE
Missing Format_Settings_SliceCount_String from schema

### ISSUE THREAD

**Issue by plondino** [MediaArea/MediaAreaXml#71]
I am running a file through mediainfo using the binary and getting a schema error for the field:

`<Format_Settings_SliceCount_String>10 slices per frame</Format_Settings_SliceCount_String>`

Tested with both lambda x86_64 and the 24.01.1 version for MacOS: [https://mediaarea.net/download](https://mediaarea.net/download/binary/libmediainfo0/24.01/MediaInfo_DLL_24.01_Mac_x86_64+arm64.tar.bz2)

This field doesn't show up in the 24.01 GUI version from the App Store however.

**Comment by JeromeMartinez** [comment]
This time [I updated the XSD early](https://github.com/MediaArea/MediaAreaXml/pull/69), but without "_String" stuff because the XSD is for without " --full" option.

```
$ mediainfo file.mp4 --Output=XML | grep SliceCount
<Format_Settings_SliceCount>12</Format_Settings_SliceCount>
$ mediainfo file.mp4 --Output=XML --full | grep  SliceCount
<Format_Settings_SliceCount>12</Format_Settings_SliceCount>
<Format_Settings_SliceCount_String>12 slices per frame</Format_Settings_SliceCount_String>
```

Do you have `Format_Settings_SliceCount_String` without " --full" in your options?

**Comment by plondino** [comment]
No, but we have been using the `--full` flag in workflow for some time now and not had an issue - I didn't realize the schema didn't apply to full.  Is there a separate schema that encompasses the extra fields?

**Comment by plondino** [comment]
Actually to be clear we are using the Python wrapper around the binary with the following options:

```        
self.mediainfo.Option_Static('Output', 'XML')
self.mediainfo.Option_Static('Complete', self.verbose)
```

Not sure if "Complete" and "full" mean the same thing.

**Comment by plondino** [comment]
I can confirm that leaving out the "Complete" option does not produce the SliceCount_String field.

**Comment by JeromeMartinez** [comment]
"Complete" and "full" are synonyms there.

My mistake, the XSD contains the list for all including complete parsing, I forgot when I created the update :(, so was sure I did it correctly... But I did not.
Updated.
